### ISSUE TITLE
Hacer diagrama Entidad-Relación de las BD

### ISSUE THREAD

**Issue by MaeMazcort** [omegaup/OFMI-website-2023#3]
Tiene que contemplar todo el sistema de cómo se va a guardar y relacionar la información.

Ver detalles -> [link](https://docs.google.com/document/d/1V4-4sSbbvZ1orqhIyDvQ5UDNxrY2kffpBsvNT3-fxh4/edit?usp=sharing&authuser=1)

**Comment by Mau-MD** [comment]
<img width="1480" alt="CleanShot 2023-03-19 at 20 04 49@2x" src="https://user-images.githubusercontent.com/74751751/226237279-c4a32298-022b-46b8-929e-299f0d86a681.png">
